data_filepath:
  train:
    "./Data/data_num_4000_r_1.5/v_30/train"
  val:
    "./Data/data_num_4000_r_1.5/v_30/val"
  test:
    "./Data/data_num_4000_r_1.5/v_30/test"

log_dirpath:
  train:
    "./logs/train_loss"
  val:
    "./logs/val_acc"
weights_dirpath:
  mcformer:
    "./Weights/MCFormer/"
  dnn:
    "./Weights/DNN/"
weights_name:
  mcformer:
    "Model_MCFormer_brownian_n_4000_r_1.5_v_30.pth"
  dnn:
    "Model_DNN_1layers_brownian_n_4000_r_1.5_v_30.pth"


